apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: terraform-kubectl
spec:
#  serviceAccountName: jenkins

  containers:
    - name: terraform
      image: marinyuk/jenkins-agent:v-1.0.0-autoscaller
      imagePullPolicy: IfNotPresent
      command:
        - cat
      tty: true
      workingDir: /home/jenkins/agent

  restartPolicy: Never